"""Shared application defaults."""

DEFAULT_ITEMS_PER_PAGE = 25
DEFAULT_CACHE_PAGES = 3
DEFAULT_CACHE_MAX_SIZE = DEFAULT_ITEMS_PER_PAGE * DEFAULT_CACHE_PAGES
DEFAULT_AUDIO_TRANSPORT = "mp3_cached"
DEFAULT_AUDIO_MP3_BITRATE = "128k"
DEFAULT_AUDIO_CACHE_MAX_AGE = 300
DEFAULT_AUDIO_STALE_WHILE_REVALIDATE = 60
DEFAULT_AUDIO_STALE_IF_ERROR = 86400
DEFAULT_AUDIO_LEGACY_FILENAME_ROUTE = True
