"""Shared application defaults."""

DEFAULT_ITEMS_PER_PAGE = 25
DEFAULT_CACHE_PAGES = 3
DEFAULT_CACHE_MAX_SIZE = DEFAULT_ITEMS_PER_PAGE * DEFAULT_CACHE_PAGES
DEFAULT_AUDIO_TRANSPORT = "mp3_cached"
DEFAULT_AUDIO_MP3_BITRATE = "128k"
